import api from '../api';
import type { Attendance, AttendanceFormData, ApiResponse } from '@/types';



















































































































































































































































































































































































































































































































































































































































































































































































}    );        </div>            </div>                )}                    </div>                        </div>                            ))}                                </div>                                    </div>                                        </div>                                            </button>                                                Supprimer                                            <button onClick={() => deleteNotification(n.id)} className="text-xs text-gray-400 hover:text-red-500 transition-colors">                                            )}                                                </button>                                                    Marquer lu                                                <button onClick={() => markRead(n.id)} className="text-xs font-semibold text-amber-600 hover:underline">                                            {!n.read && (                                        <div className="flex items-center gap-2 flex-shrink-0">                                        </div>                                            </div>                                                <p className="text-xs text-gray-400 mt-1">{n.date}</p>                                                <p className="text-sm text-gray-800 font-medium">{n.text}</p>                                            <div>                                            </div>                                                <Bell size={16} className={n.read ? 'text-gray-400' : 'text-amber-500'} />                                            <div className={`w-9 h-9 rounded-xl flex items-center justify-center flex-shrink-0 ${n.read ? 'bg-gray-100' : 'bg-amber-100'}`}>                                        <div className="flex items-start gap-3">                                    <div className="flex items-start justify-between gap-4">                                <div key={n.id} className={`bg-white rounded-2xl border p-5 transition-all ${n.read ? 'border-gray-100 opacity-70' : 'border-amber-200 shadow-sm shadow-amber-100'}`}>                            ) : notifications.map(n => (                                </div>                                    <p className="text-gray-500 font-medium">Aucune notification envoyée</p>                                    <BellRing size={40} className="mx-auto text-gray-300 mb-3" />                                <div className="bg-white rounded-2xl border border-gray-100 p-12 text-center">                            {notifications.length === 0 ? (                        <div className="space-y-3">                        {/* Messages list */}                        </div>                            </div>                                </button>                                    <Send size={16} /> Envoyer                                >                                    className="px-5 py-3 bg-amber-400 hover:bg-amber-500 text-black font-bold rounded-xl transition-all disabled:opacity-40 flex items-center gap-2 self-end"                                    disabled={!newNote.trim()}                                    onClick={sendNotification}                                <button                                />                                    className="flex-1 px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-amber-400/30 focus:border-amber-400 outline-none resize-none text-sm"                                    rows={3}                                    placeholder="Écrire une notification ou un message..."                                    onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendNotification(); }}}                                    onChange={e => setNewNote(e.target.value)}                                    value={newNote}                                <textarea                            <div className="flex gap-3">                            </h3>                                Envoyer un message à cet enseignant                                <Megaphone size={14} className="inline mr-2 text-amber-500" />                            <h3 className="text-sm font-bold text-gray-400 uppercase tracking-widest mb-4">                        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5">                        {/* Compose */}                    <div className="space-y-6">                {activeTab === 'notifications' && (                {/* ── NOTIFICATIONS ── */}                )}                    </div>                        </div>                            </div>                                })}                                    );                                        </div>                                            </div>                                                </div>                                                    <span className="font-bold text-amber-600">{hoursPerWeek.toFixed(1)}h</span>                                                    <span>Heures/sem.</span>                                                <div className="flex justify-between">                                                </div>                                                    <span className="font-bold text-gray-800">{grp.timeSlots?.length || 0}</span>                                                    <span>Séances/sem.</span>                                                <div className="flex justify-between">                                                </div>                                                    <span className="font-bold text-gray-800">{grp._count.students}</span>                                                    <span>Élèves</span>                                                <div className="flex justify-between">                                            <div className="space-y-1.5 text-xs text-gray-600">                                            <p className="font-bold text-gray-800 text-sm mb-2">{grp.name}</p>                                        <div key={grp.id} className={`p-4 rounded-xl border-2 ${grp.type === 'FORMATION' ? 'border-purple-100 bg-purple-50' : 'border-blue-100 bg-blue-50'}`}>                                    return (                                    }, 0);                                        return acc + (eh * 60 + em - sh * 60 - sm) / 60;                                        const [eh, em] = slot.endTime.split(':').map(Number);                                        const [sh, sm] = slot.startTime.split(':').map(Number);                                    const hoursPerWeek = (grp.timeSlots || []).reduce((acc, slot) => {                                {teacher.groups.map(grp => {                            <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-4">                            <h3 className="text-sm font-bold text-gray-400 uppercase tracking-widest mb-5">Récapitulatif des cours</h3>                        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">                        {/* Groups Overview */}                        </div>                            )}                                </div>                                    ))}                                        </div>                                            </span>                                                {item.grp.type === 'FORMATION' ? 'Formation' : 'Soutien'}                                            <span className={`ml-2 px-2 py-1 rounded-full text-xs font-bold ${item.grp.type === 'FORMATION' ? 'bg-purple-100 text-purple-600' : 'bg-blue-100 text-blue-600'}`}>                                            </div>                                                <p className="text-sm text-gray-500">{item.startTime} — {item.endTime}</p>                                                <p className="font-bold text-amber-600">{DAYS_FR[item.day] || item.day}</p>                                            <div className="text-right">                                            </div>                                                </div>                                                    {item.grp.room && <span className="flex items-center gap-1"><Hash size={12} />{item.grp.room}</span>}                                                    {item.grp.subject && <span className="flex items-center gap-1"><BookOpen size={12} />{item.grp.subject}</span>}                                                <div className="flex items-center gap-3 mt-1 text-sm text-gray-500">                                                <p className="font-bold text-gray-800">{item.grp.name}</p>                                            <div className="flex-1">                                            </div>                                                <Calendar size={20} className="text-white" />                                            <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-amber-400 to-yellow-500 flex items-center justify-center flex-shrink-0 shadow-sm shadow-amber-300/30">                                        <div key={item.key} className="flex items-center gap-4 p-4 rounded-xl border border-gray-100 hover:border-amber-200 hover:bg-amber-50/30 transition-all group">                                    ).sort((a, b) => a.startTime.localeCompare(b.startTime)).map(item => (                                        (grp.timeSlots || []).map((slot, i) => ({ ...slot, grp, key: `${grp.id}-${i}` }))                                    {teacher.groups.flatMap(grp =>                                <div className="space-y-3">                            ) : (                                <p className="text-gray-400 text-center py-8">Aucun cours planifié</p>                            {teacher.groups.length === 0 ? (                            <h3 className="text-sm font-bold text-gray-400 uppercase tracking-widest mb-5">Planning hebdomadaire</h3>                        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">                        {/* Weekly Schedule */}                    <div className="space-y-6">                {activeTab === 'cours' && (                {/* ── COURS & EXAMENS ── */}                )}                    </div>                        )}                            </div>                                <p className="text-gray-500 font-medium">Sélectionnez un groupe pour saisir la présence</p>                                <UserCheck size={40} className="mx-auto text-gray-300 mb-3" />                            <div className="bg-white rounded-2xl border border-gray-100 p-12 text-center">                        {!selectedGroup && (                        })()}                            );                                </div>                                    )}                                        </div>                                            </button>                                                {savingAttendance ? 'Enregistrement...' : attendanceSaved ? 'Enregistré !' : 'Enregistrer la présence'}                                                {savingAttendance ? <RefreshCw size={16} className="animate-spin" /> : attendanceSaved ? <CheckCircle2 size={16} /> : <Save size={16} />}                                            >                                                className={`flex items-center gap-2 px-6 py-2.5 rounded-xl font-bold text-sm transition-all ${attendanceSaved ? 'bg-emerald-500 text-white' : 'bg-amber-400 hover:bg-amber-500 text-black'} disabled:opacity-60`}                                                disabled={savingAttendance}                                                onClick={saveAttendance}                                            <button                                        <div className="p-5 border-t border-gray-100 flex justify-end">                                    {grp.students.length > 0 && (                                    {/* Save button */}                                    )}                                        </div>                                            })}                                                );                                                    </div>                                                        </div>                                                            </button>                                                                <XCircle size={14} /> Absent                                                            >                                                                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${status === 'absent' ? 'bg-red-500 text-white shadow-sm shadow-red-500/30' : 'bg-gray-100 text-gray-400 hover:bg-red-50 hover:text-red-500'}`}                                                                onClick={() => setAttendanceMap(prev => ({ ...prev, [s.id]: 'absent' }))}                                                            <button                                                            </button>                                                                <CheckCircle2 size={14} /> Présent                                                            >                                                                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${status === 'present' ? 'bg-emerald-500 text-white shadow-sm shadow-emerald-500/30' : 'bg-gray-100 text-gray-400 hover:bg-emerald-50 hover:text-emerald-500'}`}                                                                onClick={() => setAttendanceMap(prev => ({ ...prev, [s.id]: 'present' }))}                                                            <button                                                        <div className="flex items-center gap-2">                                                        </div>                                                            </div>                                                                {s.phone && <p className="text-xs text-gray-400">{s.phone}</p>}                                                                <p className="font-semibold text-gray-800">{s.name} {s.surname}</p>                                                            <div>                                                            </div>                                                                {s.name[0]}{s.surname[0]}                                                            <div className={`w-9 h-9 rounded-full flex items-center justify-center text-xs font-black ${status === 'present' ? 'bg-emerald-100 text-emerald-700' : 'bg-red-100 text-red-500'}`}>                                                            <span className="text-xs text-gray-300 font-mono w-5 text-center">{idx + 1}</span>                                                        <div className="flex items-center gap-4">                                                    <div key={s.id} className={`flex items-center justify-between px-5 py-3.5 transition-colors ${status === 'present' ? 'bg-white hover:bg-emerald-50/30' : 'bg-red-50/40 hover:bg-red-50'}`}>                                                return (                                                const status = attendanceMap[s.id] || 'present';                                            {grp.students.map((s, idx) => {                                        <div className="divide-y divide-gray-50">                                    ) : (                                        <div className="p-10 text-center text-gray-400">Aucun élève dans ce groupe</div>                                    {grp.students.length === 0 ? (                                    {/* Students list */}                                    </div>                                        </div>                                            </button>                                                Tous présents                                            >                                                className="px-3 py-1.5 bg-emerald-50 text-emerald-600 text-xs font-bold rounded-lg hover:bg-emerald-100 transition-colors"                                                }}                                                    setAttendanceMap(all);                                                    grp.students.forEach(s => { all[s.id] = 'present'; });                                                    const all: Record<string, 'present' | 'absent'> = {};                                                onClick={() => {                                            <button                                            {/* Mark all buttons */}                                            </div>                                                </span>                                                    <XCircle size={16} /> {absentCount}                                                <span className="flex items-center gap-1.5 font-bold text-red-500">                                                </span>                                                    <CheckCircle2 size={16} /> {presentCount}                                                <span className="flex items-center gap-1.5 font-bold text-emerald-600">                                            <div className="flex gap-3 text-sm">                                        <div className="flex items-center gap-4">                                        </div>                                            </p>                                                {new Date(attendanceDate).toLocaleDateString('fr-FR', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })}                                            <p className="text-sm text-gray-500 mt-0.5">                                            <h4 className="font-bold text-gray-800">{grp.name}</h4>                                        <div>                                    <div className="p-5 border-b border-gray-100 flex items-center justify-between">                                    {/* Sheet Header */}                                <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">                            return (                            const absentCount = grp.students.length - presentCount;                            const presentCount = Object.values(attendanceMap).filter(v => v === 'present').length;                            if (!grp) return null;                            const grp = teacher.groups.find(g => g.id === selectedGroup);                        {selectedGroup && (() => {                        {/* Attendance Sheet */}                        </div>                            </div>                                </div>                                    />                                        className="px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-amber-400/30 focus:border-amber-400 outline-none text-sm font-medium"                                        onChange={e => setAttendanceDate(e.target.value)}                                        value={attendanceDate}                                        type="date"                                    <input                                    <label className="text-xs font-bold text-gray-500 uppercase tracking-wider block mb-2">Date</label>                                <div>                                </div>                                    </select>                                        ))}                                            <option key={g.id} value={g.id}>{g.name} ({g._count.students} élèves)</option>                                        {teacher.groups.map(g => (                                        <option value="">— Choisir un groupe —</option>                                    >                                        className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-amber-400/30 focus:border-amber-400 outline-none bg-white text-sm font-medium"                                        onChange={e => { setSelectedGroup(e.target.value); setAttendanceSaved(false); }}                                        value={selectedGroup}                                    <select                                    <label className="text-xs font-bold text-gray-500 uppercase tracking-wider block mb-2">Groupe</label>                                <div className="flex-1">                            <div className="flex flex-col sm:flex-row gap-4">                            <h3 className="text-sm font-bold text-gray-400 uppercase tracking-widest mb-4">Saisir une feuille de présence</h3>                        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5">                        {/* Controls */}                    <div className="space-y-6">                {activeTab === 'presence' && (                {/* ── PRÉSENCE ── */}                )}                    </div>                        ))}                            </div>                                )}                                    </div>                                        Aucun élève dans ce groupe                                    <div className="border-t border-gray-100 p-6 text-center text-gray-400 text-sm">                                {expandedGroups.has(grp.id) && grp.students.length === 0 && (                                )}                                    </div>                                        </table>                                            </tbody>                                                })}                                                    );                                                        </tr>                                                            </td>                                                                </span>                                                                    {presentCount}/{totalSessions}                                                                <span className={`px-2 py-1 rounded-lg text-xs font-bold ${presentCount >= totalSessions * 0.75 ? 'bg-green-100 text-green-600' : 'bg-orange-100 text-orange-600'}`}>                                                            <td className="px-5 py-3 text-center">                                                            <td className="px-5 py-3 text-gray-600">{s.phone || '—'}</td>                                                            <td className="px-5 py-3 text-gray-600 text-xs">{s.schoolLevel || '—'}</td>                                                            </td>                                                                </div>                                                                    <span className="font-semibold text-gray-800">{s.name} {s.surname}</span>                                                                    </div>                                                                        {s.name[0]}{s.surname[0]}                                                                    <div className="w-8 h-8 rounded-full bg-gradient-to-br from-slate-200 to-slate-300 flex items-center justify-center text-slate-600 text-xs font-bold">                                                                <div className="flex items-center gap-3">                                                            <td className="px-5 py-3">                                                            <td className="px-5 py-3 text-gray-400 font-mono text-xs">{idx + 1}</td>                                                        <tr key={s.id} className="border-t border-gray-50 hover:bg-gray-50 transition-colors">                                                    return (                                                    const totalSessions = s.attendance?.length || 0;                                                    const presentCount = s.attendance?.filter(a => a.status === 'present').length || 0;                                                {grp.students.map((s, idx) => {                                            <tbody>                                            </thead>                                                </tr>                                                    <th className="px-5 py-3 text-center">Présences</th>                                                    <th className="px-5 py-3 text-left">Téléphone</th>                                                    <th className="px-5 py-3 text-left">Niveau</th>                                                    <th className="px-5 py-3 text-left">Nom complet</th>                                                    <th className="px-5 py-3 text-left">#</th>                                                <tr className="bg-gray-50 text-xs font-bold text-gray-400 uppercase tracking-wider">                                            <thead>                                        <table className="w-full text-sm">                                    <div className="border-t border-gray-100">                                {expandedGroups.has(grp.id) && grp.students.length > 0 && (                                )}                                    </div>                                        ))}                                            </span>                                                {DAYS_FR[slot.day] || slot.day} {slot.startTime}–{slot.endTime}                                                <Clock size={11} />                                            <span key={i} className="flex items-center gap-1.5 px-3 py-1 bg-amber-50 text-amber-700 rounded-full text-xs font-semibold border border-amber-100">                                        {grp.timeSlots.map((slot, i) => (                                    <div className="px-5 py-2 bg-gray-50 border-t border-gray-100 flex flex-wrap gap-2">                                {grp.timeSlots && grp.timeSlots.length > 0 && (                                {/* Horaires */}                                </button>                                    </div>                                        {expandedGroups.has(grp.id) ? <ChevronUp size={20} className="text-gray-400" /> : <ChevronDown size={20} className="text-gray-400" />}                                        </div>                                            <p className="text-xs text-gray-400">élève{grp._count.students !== 1 ? 's' : ''}</p>                                            <p className="text-2xl font-black text-gray-800">{grp._count.students}</p>                                        <div className="text-right">                                    <div className="flex items-center gap-4">                                    </div>                                        </div>                                            </div>                                                {grp.room && <span className="text-xs text-gray-500 flex items-center gap-1"><Hash size={11} /> {grp.room}</span>}                                                {grp.level && <span className="text-xs text-gray-500 flex items-center gap-1"><GraduationCap size={11} /> {grp.level}</span>}                                                {grp.subject && <span className="text-xs text-gray-500 flex items-center gap-1"><BookOpen size={11} /> {grp.subject}</span>}                                            <div className="flex items-center gap-3 mt-1">                                            <p className="font-bold text-gray-800">{grp.name}</p>                                        <div className="text-left">                                        </div>                                            {grp.type === 'FORMATION' ? 'F' : 'S'}                                        <div className={`w-12 h-12 rounded-xl flex items-center justify-center font-bold text-white text-lg ${grp.type === 'FORMATION' ? 'bg-gradient-to-br from-purple-500 to-indigo-600' : 'bg-gradient-to-br from-blue-500 to-cyan-600'}`}>                                    <div className="flex items-center gap-4">                                >                                    className="w-full flex items-center justify-between p-5 hover:bg-gray-50 transition-colors"                                    onClick={() => toggleGroup(grp.id)}                                <button                            <div key={grp.id} className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">                        ) : teacher.groups.map(grp => (                            </div>                                <p className="text-gray-500 font-medium">Aucun groupe assigné</p>                                <Layers size={40} className="mx-auto text-gray-300 mb-3" />                            <div className="bg-white rounded-2xl p-12 text-center border border-gray-100">                        {teacher.groups.length === 0 ? (                    <div className="space-y-4">                {activeTab === 'groupes' && (                {/* ── GROUPES ── */}                )}                    </div>                        </div>                            </div>                                </div>                                    </div>                                        ))}                                            <span key={l} className="px-3 py-1 bg-blue-100 text-blue-700 rounded-full text-xs font-semibold">{l}</span>                                        {teacher.levels.map(l => (                                    <div className="flex flex-wrap gap-2">                                    <p className="text-xs text-gray-400 mb-2">Niveaux</p>                                <div>                                </div>                                    </div>                                        ))}                                            <span key={s} className="px-3 py-1 bg-amber-100 text-amber-700 rounded-full text-xs font-semibold">{s}</span>                                        {teacher.specialties.map(s => (                                    <div className="flex flex-wrap gap-2">                                    <p className="text-xs text-gray-400 mb-2">Matières enseignées</p>                                <div className="mb-3">                                <h3 className="text-sm font-bold text-gray-400 uppercase tracking-widest mb-4">Matières & Niveaux</h3>                            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">                            {/* Specialties & Levels */}                            </div>                                </div>                                    )}                                        </a>                                            <span className="text-sm font-semibold text-green-700">WhatsApp: {teacher.socialMedia.whatsapp}</span>                                            <Phone size={16} className="text-green-600" />                                            className="flex items-center gap-3 p-3 bg-green-50 rounded-xl hover:bg-green-100 transition-colors">                                        <a href={`https://wa.me/${teacher.socialMedia.whatsapp.replace(/\D/g, '')}`} target="_blank" rel="noreferrer"                                    {teacher.socialMedia?.whatsapp && (                                    </div>                                        <TrendingUp className="text-emerald-500" size={22} />                                        </div>                                            </p>                                                    : `${teacher.hourlyRate} MAD`}                                                    ? `${teacher.commission || 0}%`                                                {teacher.paymentType === 'PERCENTAGE'                                            <p className="font-bold text-gray-800">                                            </p>                                                {teacher.paymentType === 'HOURLY' ? 'Taux horaire' : teacher.paymentType === 'PERCENTAGE' ? 'Commission' : 'Salaire mensuel'}                                            <p className="text-xs text-gray-500">                                        <div>                                    <div className="flex items-center justify-between p-3 bg-emerald-50 rounded-xl">                                    </div>                                        <DollarSign className="text-amber-500" size={22} />                                        </div>                                            </p>                                                {teacher.paymentType === 'HOURLY' ? 'Par heure' : teacher.paymentType === 'FIXED' ? 'Salaire fixe' : 'Commission (%)'}                                            <p className="font-bold text-gray-800">                                            <p className="text-xs text-gray-500">Type de paiement</p>                                        <div>                                    <div className="flex items-center justify-between p-3 bg-amber-50 rounded-xl">                                <div className="space-y-4">                                <h3 className="text-sm font-bold text-gray-400 uppercase tracking-widest mb-5">Informations professionnelles</h3>                            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">                        <div className="space-y-6">                        {/* Professional Info */}                        </div>                            </div>                                ))}                                    </div>                                        </div>                                            <p className="text-sm font-semibold text-gray-800">{item.value}</p>                                            <p className="text-xs text-gray-400">{item.label}</p>                                        <div>                                        </div>                                            <item.icon size={16} className="text-amber-500" />                                        <div className="w-9 h-9 rounded-lg bg-amber-50 flex items-center justify-center flex-shrink-0">                                    <div key={item.label} className="flex items-center gap-3">                                ].map(item => (                                    { label: 'Statut', value: teacher.status === 'Active' ? 'Actif' : 'Inactif', icon: Activity },                                    { label: 'Genre', value: teacher.gender || '—', icon: User },                                    { label: 'CIN', value: teacher.cin || '—', icon: Hash },                                    { label: 'Téléphone', value: teacher.phone || '—', icon: Phone },                                    { label: 'Email', value: teacher.email || '—', icon: Mail },                                    { label: 'Nom complet', value: teacher.name, icon: User },                                {[                            <div className="space-y-4">                            <h3 className="text-sm font-bold text-gray-400 uppercase tracking-widest mb-5">Informations personnelles</h3>                        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">                        {/* Personal Info */}                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">                {activeTab === 'profil' && (                {/* ── PROFIL ── */}            <div className="p-6 max-w-6xl mx-auto">            {/* Content */}            </div>                </div>                    ))}                        </button>                            )}                                </span>                                    {tab.count}                                <span className="ml-1 bg-amber-400 text-black text-xs font-black rounded-full w-5 h-5 flex items-center justify-center">                            {tab.count !== undefined && tab.count > 0 && (                            {tab.label}                            <tab.icon size={16} />                        >                            }`}                                    : 'border-transparent text-slate-400 hover:text-white'                                    ? 'border-amber-400 text-amber-300'                                activeTab === tab.id                            className={`flex items-center gap-2 px-5 py-3 text-sm font-semibold whitespace-nowrap border-b-2 transition-all ${                            onClick={() => setActiveTab(tab.id)}                            key={tab.id}                        <button                    {tabs.map(tab => (                <div className="flex overflow-x-auto scrollbar-hide">                {/* Tabs */}                </div>                    </div>                        ))}                            </div>                                <p className="text-xs text-slate-400">{stat.label}</p>                                <p className="text-xl font-black text-white">{stat.value}</p>                                <stat.icon size={16} className={`${stat.color} mx-auto mb-1`} />                            <div key={stat.label} className="text-center bg-white/5 rounded-xl px-4 py-3 min-w-[80px]">                        ].map(stat => (                            { label: 'MAD/h', value: teacher.paymentType === 'FIXED' ? teacher.hourlyRate : teacher.hourlyRate, icon: DollarSign, color: 'text-emerald-300' },                            { label: 'Élèves', value: totalStudents, icon: Users, color: 'text-blue-300' },                            { label: 'Groupes', value: teacher._count.groups, icon: Layers, color: 'text-purple-300' },                        {[                    <div className="flex gap-4">                    {/* Stats */}                    </div>                        </div>                            ))}                                <span key={l} className="px-2 py-0.5 bg-blue-400/20 text-blue-300 rounded-full text-xs font-semibold border border-blue-400/30">{l}</span>                            {teacher.levels.slice(0, 3).map(l => (                            ))}                                <span key={s} className="px-2 py-0.5 bg-amber-400/20 text-amber-300 rounded-full text-xs font-semibold border border-amber-400/30">{s}</span>                            {teacher.specialties.slice(0, 4).map(s => (                        <div className="flex flex-wrap items-center gap-2 mt-2">                        <h1 className="text-2xl font-black text-white">{teacher.name}</h1>                    <div className="flex-1">                    {/* Info */}                    </div>                        <span className={`absolute -bottom-1 -right-1 w-5 h-5 rounded-full border-2 border-[#1e293b] ${teacher.status === 'Active' ? 'bg-emerald-400' : 'bg-gray-400'}`} />                        </div>                            {initials}                        <div className="w-20 h-20 rounded-2xl bg-gradient-to-br from-amber-400 to-yellow-500 flex items-center justify-center text-white font-black text-2xl shadow-xl shadow-amber-500/30">                    <div className="relative">                    {/* Avatar */}                <div className="px-6 pb-6 flex flex-col lg:flex-row items-start lg:items-center gap-6">                </div>                    <span className="text-sm text-amber-300 font-medium">{teacher.name}</span>                    <ChevronRight size={14} className="text-slate-500" />                    <span className="text-sm text-slate-400">Enseignants</span>                    </button>                        <ArrowLeft size={20} />                    >                        className="p-2 hover:bg-white/10 rounded-lg transition-colors"                        onClick={() => router.push('/admin/teachers')}                    <button                <div className="px-6 py-4 flex items-center gap-3">            <div className="bg-gradient-to-r from-[#1e293b] via-[#2e3b4e] to-[#1e293b] text-white">            {/* Header Banner */}        <div className="min-h-screen bg-gray-50">    return (    ];        { id: 'notifications', label: 'Notifications', icon: Bell, count: unreadCount || undefined },        { id: 'cours', label: 'Cours & Examens', icon: ClipboardList },        { id: 'presence', label: 'Présence', icon: UserCheck },        { id: 'groupes', label: 'Groupes & Élèves', icon: Layers, count: teacher._count.groups },        { id: 'profil', label: 'Profil', icon: User },    const tabs: { id: Tab; label: string; icon: any; count?: number }[] = [    const unreadCount = notifications.filter(n => !n.read).length;    const initials = teacher.name.split(' ').map(w => w[0]).join('').slice(0, 2).toUpperCase();    const totalStudents = teacher.groups.reduce((acc, g) => acc + g._count.students, 0);    );        </div>            </div>                </button>                    <ArrowLeft size={16} /> Retour                <button onClick={() => router.back()} className="mt-4 text-amber-500 hover:underline flex items-center gap-1 mx-auto">                <p className="text-gray-500 text-lg font-medium">Enseignant introuvable</p>                <User size={48} className="mx-auto text-gray-300 mb-4" />            <div className="text-center">        <div className="flex items-center justify-center h-96">    if (!teacher) return (    );        </div>            </div>                <p className="text-gray-500 font-medium">Chargement du tableau de bord...</p>                <div className="w-12 h-12 border-4 border-amber-400 border-t-transparent rounded-full animate-spin" />            <div className="flex flex-col items-center gap-4">        <div className="flex items-center justify-center h-96">    if (loading) return (    };        });            return s;            s.has(id) ? s.delete(id) : s.add(id);            const s = new Set(prev);        setExpandedGroups(prev => {    const toggleGroup = (id: string) => {    };        localStorage.setItem(`teacher_notifications_${teacherId}`, JSON.stringify(updated));        setNotifications(updated);        const updated = notifications.filter(n => n.id !== id);    const deleteNotification = (id: string) => {    };        localStorage.setItem(`teacher_notifications_${teacherId}`, JSON.stringify(updated));        setNotifications(updated);        const updated = notifications.map(n => n.id === id ? { ...n, read: true } : n);    const markRead = (id: string) => {    };        setNewNote('');        localStorage.setItem(`teacher_notifications_${teacherId}`, JSON.stringify(updated));        setNotifications(updated);        const updated = [note, ...notifications];        const note = { id: Date.now().toString(), text: newNote.trim(), date: new Date().toLocaleString('fr-FR'), read: false };        if (!newNote.trim()) return;    const sendNotification = () => {    };        }            setSavingAttendance(false);        } finally {            console.error(e);        } catch (e) {            setTimeout(() => setAttendanceSaved(false), 3000);            setAttendanceSaved(true);            await bulkSaveAttendance(records);            }));                status: attendanceMap[s.id] || 'present'                date: attendanceDate,                studentId: s.id,            const records = grp.students.map(s => ({        try {        setSavingAttendance(true);        if (!grp) return;        const grp = teacher.groups.find(g => g.id === selectedGroup);        if (!selectedGroup || !attendanceDate || !teacher) return;    const saveAttendance = async () => {    }, [selectedGroup, attendanceDate, teacher]);        }).catch(() => {});            }                setAttendanceMap(fresh);                });                    fresh[a.studentId] = a.status;                res.attendances.forEach((a: any) => {                const fresh: Record<string, 'present' | 'absent'> = { ...map };            if (res?.attendances?.length) {        getAttendanceByGroup(selectedGroup, attendanceDate).then(res => {        // Try to load existing attendance for this group+date        setAttendanceMap(map);        grp.students.forEach(s => { map[s.id] = 'present'; });        const map: Record<string, 'present' | 'absent'> = {};        // Default all to present        setAttendanceDate(attendanceDate);        if (!grp) return;        const grp = teacher.groups.find(g => g.id === selectedGroup);        if (!selectedGroup || !attendanceDate || !teacher) return;    useEffect(() => {    // When group changes, pre-load existing attendance for selected date    useEffect(() => { load(); }, [load]);    }, [teacherId]);        }            setLoading(false);        } finally {            console.error(e);        } catch (e) {            if (stored) setNotifications(JSON.parse(stored));            const stored = localStorage.getItem(`teacher_notifications_${teacherId}`);            // Load notifications from localStorage            setTeacher(data);            const data = await teachersService.getById(teacherId) as unknown as TeacherDetail;        try {        setLoading(true);    const load = useCallback(async () => {    const [expandedGroups, setExpandedGroups] = useState<Set<string>>(new Set());    // Groups expand state    const [newNote, setNewNote] = useState('');    const [notifications, setNotifications] = useState<{ id: string; text: string; date: string; read: boolean }[]>([]);    // Notifications state    const [attendanceSaved, setAttendanceSaved] = useState(false);    const [savingAttendance, setSavingAttendance] = useState(false);    const [attendanceMap, setAttendanceMap] = useState<Record<string, 'present' | 'absent'>>({});    const [attendanceDate, setAttendanceDate] = useState(() => new Date().toISOString().split('T')[0]);    const [selectedGroup, setSelectedGroup] = useState<string>('');    // Attendance state    const [activeTab, setActiveTab] = useState<Tab>('profil');    const [loading, setLoading] = useState(true);    const [teacher, setTeacher] = useState<TeacherDetail | null>(null);    const teacherId = params.id as string;    const router = useRouter();    const params = useParams();export default function TeacherDashboard() {// ─── Main Component ────────────────────────────────────────────────};    'الأربعاء': 'Mercredi', 'الخميس': 'Jeudi', 'الجمعة': 'Vendredi', 'السبت': 'Samedi'    'الأحد': 'Dimanche', 'الاثنين': 'Lundi', 'الثلاثاء': 'Mardi',const DAYS_FR: Record<string, string> = {type Tab = 'profil' | 'groupes' | 'presence' | 'cours' | 'notifications';}    createdAt: string;    _count: { groups: number };    groups: Group[];    socialMedia?: { whatsapp?: string; linkedin?: string };    levels: string[];    specialties: string[];    commission?: number;    paymentType: string;    hourlyRate: number;    status: string;    gender?: string;    cin?: string;    phone?: string;    email?: string;    name: string;    id: string;interface TeacherDetail {}    _count: { students: number };    students: StudentInGroup[];    timeSlots?: { day: string; startTime: string; endTime: string }[];    room?: string;    level?: string;    subject?: string;    type: string;    name: string;    id: string;interface Group {}    attendance?: { id: string; date: string; status: string }[];    schoolLevel?: string;    email?: string;    phone?: string;    surname: string;    name: string;    id: string;interface StudentInGroup {// ─── Types ────────────────────────────────────────────────────────import api from '@/lib/api';import { bulkSaveAttendance, getAttendanceByGroup } from '@/lib/services/attendance';import { teachersService } from '@/lib/services/teachers';} from 'lucide-react';    DollarSign, TrendingUp, Hash, ChevronDown, ChevronUp, Edit2    LayoutGrid, Layers, UserCheck, ClipboardList, Megaphone,    Award, Activity, Save, RefreshCw, Bell, BellRing, Send,    Clock, CheckCircle2, XCircle, ChevronRight, ArrowLeft, Star,    User, Mail, Phone, BookOpen, GraduationCap, Users, Calendar,import {import { useParams, useRouter } from 'next/navigation';import { useState, useEffect, useCallback } from 'react';
export async function getAttendanceByStudent(studentId: string): Promise<Attendance[]> {
    const response = await api.get<ApiResponse<Attendance[]>>(`/attendance/student/${studentId}`);
    return response.data.data;
}

export async function createAttendance(data: AttendanceFormData): Promise<Attendance> {
    const response = await api.post<ApiResponse<Attendance>>('/attendance', data);
    return response.data.data;
}

export async function bulkSaveAttendance(records: { studentId: string; date: string; status: string }[]): Promise<any> {
    const response = await api.post('/attendance/bulk', { records });
    return response.data.data;
}

export async function getAttendanceByGroup(groupId: string, date?: string): Promise<any> {
    const params = date ? { date } : {};
    const response = await api.get(`/attendance/group/${groupId}`, { params });
    return response.data.data;
}
